export { default as Home } from './Home.vue'
export { default as Explore } from './Explore.vue'
export { default as About } from './About.vue'
export { default as Search } from './Search.vue'
export { default as SearchMolecule } from './SearchMolecule.vue'